// fetch-lists.ts — developer-only helper that pulls the upstream filter
// lists into apps/extension/vendor/. Run via `pnpm -F @ad-blocker/extension
// lists:fetch`.
//
// Why this isn't part of the build:
//   - Network access from CI is discouraged — we want deterministic builds,
//     and a silently-updated EasyList would invalidate every lockfile-based
//     cache. The vendored files are the source of truth for CI; this
//     script refreshes them locally, committed as an explicit change.
//   - EasyList changes frequently. Tying the extension build to a live HTTP
//     fetch would mean failing builds whenever easylist.to has a hiccup.
//
// ETag caching is implemented so re-runs are cheap. We store the last ETag
// per list in vendor/manifest.json and send it back as `If-None-Match`.
// Upstream answers 304 when nothing changed, and we leave the existing file
// on disk untouched. Reported changes bubble up in the script's output.
//
// Integrity: we also store a SHA-256 of each file. That way, even if the
// upstream server returns a new ETag but identical bytes (happens more
// often than you'd expect when lists rebuild their own caches), we can
// still report "no real change" cleanly.

import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Configuration.
// ---------------------------------------------------------------------------

/** One filter list to fetch. */
interface ListSource {
  /** Short id used for the vendored filename (`<id>.txt`) and manifest key. */
  id: string;
  /** Upstream URL. Must be HTTPS — we don't want MITM-able fetches here. */
  url: string;
}

/**
 * The canonical upstream URLs. Intentionally hard-coded — these are the
 * lists the extension ships by default. If we add more, they come through
 * this list; custom subscriptions are a later feature (not Phase 4b).
 */
const SOURCES: readonly ListSource[] = [
  { id: 'easylist', url: 'https://easylist.to/easylist/easylist.txt' },
  {
    id: 'easyprivacy',
    url: 'https://easylist.to/easylist/easyprivacy.txt',
  },
  // Annoyance-class lists. These two are the canonical EasyList-project
  // companions to the core lists above:
  //   - easylist-cookie targets cookie-consent banners (GDPR notices,
  //     "we use cookies" overlays, etc.).
  //   - fanboy-annoyance targets newsletter/popups, "in-page" social
  //     widgets, anti-adblock walls, and similar interstitials.
  // Both ship default-OFF (see SOURCE_DEFAULTS in src/shared/messages.ts)
  // because they have a higher site-breakage rate than the baseline lists.
  {
    id: 'easylist-cookie',
    url: 'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt',
  },
  {
    id: 'easylist-annoyances',
    url: 'https://easylist.to/easylist/fanboy-annoyance.txt',
  },
] as const;

// ---------------------------------------------------------------------------
// Path layout.
// ---------------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const EXT_ROOT = resolve(HERE, '..');
const VENDOR_DIR = join(EXT_ROOT, 'vendor');
const MANIFEST_PATH = join(VENDOR_DIR, 'manifest.json');

// ---------------------------------------------------------------------------
// Manifest shape.
// ---------------------------------------------------------------------------

/** Per-list metadata persisted between runs. */
interface ListManifestEntry {
  /** Upstream URL used on the last fetch. Recorded so we notice if the
   *  configured URL changes underneath a cached ETag. */
  url: string;
  /** The ETag header value from the last 200 response, verbatim. May be a
   *  weak ETag (`W/"..."`) — we forward the whole string. */
  etag: string | null;
  /** SHA-256 of the list bytes, lowercase hex. Used to detect no-op
   *  content changes when the server rotates ETags but the bytes match. */
  sha256: string;
  /** Size of the file in bytes. Informational only. */
  bytes: number;
  /** ISO timestamp of the last time we successfully wrote the file. */
  lastFetchedAt: string;
  /** ISO timestamp of the most recent attempt (200 or 304). Lets a
   *  developer see "this was checked yesterday but hasn't changed since
   *  last month" at a glance. */
  lastCheckedAt: string;
}

interface VendorManifest {
  /** Human note — no code reads this; it's for the committer. */
  note: string;
  /** Keyed by `ListSource.id`. */
  entries: Record<string, ListManifestEntry>;
}

const EMPTY_MANIFEST: VendorManifest = {
  note:
    'Generated by scripts/fetch-lists.ts. Do not edit by hand — rerun the ' +
    'script to refresh. The accompanying .txt files in this directory are ' +
    'the actual filter lists and are gitignored.',
  entries: {},
};

// ---------------------------------------------------------------------------
// Fetch + cache logic.
// ---------------------------------------------------------------------------

/** Result of a single list's fetch attempt, for the CLI summary. */
type FetchOutcome =
  | { kind: 'first-fetch'; bytes: number }
  | { kind: 'updated'; bytes: number; oldBytes: number }
  | { kind: 'etag-same' }
  | { kind: 'bytes-same'; bytes: number };

/**
 * Compute a SHA-256 over a buffer, returned as lowercase hex. Uses Node's
 * `crypto` rather than WebCrypto to avoid an async `await` where we don't
 * need one — the buffers we're hashing are small enough that the sync path
 * is simpler and faster.
 */
function sha256Hex(buf: Uint8Array): string {
  return createHash('sha256').update(buf).digest('hex');
}

/** Read an existing manifest or return an empty shell on first run. */
function loadManifest(): VendorManifest {
  if (!existsSync(MANIFEST_PATH)) return structuredClone(EMPTY_MANIFEST);
  try {
    const raw = readFileSync(MANIFEST_PATH, 'utf8');
    // Defensive parse — a developer may have hand-edited this in a merge
    // conflict. Fall back to the empty shell on any structural issue so
    // we re-fetch from clean rather than propagating bad state.
    const parsed = JSON.parse(raw) as unknown;
    if (
      !parsed ||
      typeof parsed !== 'object' ||
      !('entries' in parsed) ||
      typeof (parsed as { entries: unknown }).entries !== 'object'
    ) {
      return structuredClone(EMPTY_MANIFEST);
    }
    return parsed as VendorManifest;
  } catch {
    return structuredClone(EMPTY_MANIFEST);
  }
}

/** Atomic-ish manifest write: stringify, then write. We don't bother with
 *  tempfile+rename because the manifest is tiny and the failure mode of a
 *  half-written manifest is "next run re-fetches everything", which is
 *  acceptable. */
function saveManifest(m: VendorManifest): void {
  mkdirSync(dirname(MANIFEST_PATH), { recursive: true });
  writeFileSync(MANIFEST_PATH, JSON.stringify(m, null, 2) + '\n', 'utf8');
}

/**
 * Fetch one list, honoring ETag caching. Returns the outcome; the caller
 * handles disk writes and manifest updates.
 */
async function fetchList(
  source: ListSource,
  prior: ListManifestEntry | undefined,
): Promise<{
  outcome: FetchOutcome;
  /** Next manifest entry. Always returned, even on no-op (to refresh
   *  `lastCheckedAt`). */
  nextEntry: ListManifestEntry;
}> {
  const targetPath = join(VENDOR_DIR, `${source.id}.txt`);

  // Only send If-None-Match if we have both the prior ETag *and* the file
  // on disk. A missing file means we can't trust a 304 — the server would
  // say "not modified" relative to a copy we no longer have.
  const sendConditional =
    prior?.etag != null && existsSync(targetPath) && prior.url === source.url;

  const headers: Record<string, string> = {
    // Identify ourselves politely. easylist.to is served by a CDN that
    // doesn't care, but it's good etiquette.
    'User-Agent': 'ad-blocker-dev-fetch-lists/1 (+https://easylist.to)',
    Accept: 'text/plain, */*;q=0.1',
  };
  if (sendConditional && prior?.etag) {
    headers['If-None-Match'] = prior.etag;
  }

  const res = await fetch(source.url, { headers });

  const nowIso = new Date().toISOString();

  if (res.status === 304) {
    // Conditional hit — nothing to write. Refresh `lastCheckedAt` so the
    // manifest reflects the successful check.
    if (!prior) {
      // Spec-wise, the server shouldn't 304 when we didn't send
      // If-None-Match, but don't crash if it does.
      throw new Error(
        `${source.id}: server returned 304 but we have no prior manifest entry`,
      );
    }
    return {
      outcome: { kind: 'etag-same' },
      nextEntry: { ...prior, lastCheckedAt: nowIso },
    };
  }

  if (!res.ok) {
    throw new Error(
      `${source.id}: HTTP ${res.status} ${res.statusText} from ${source.url}`,
    );
  }

  const bytes = new Uint8Array(await res.arrayBuffer());
  const sha = sha256Hex(bytes);
  // Normalize the ETag capture — `headers.get` returns the combined value
  // per the Fetch spec; it's already a valid ETag for round-tripping.
  const newEtag = res.headers.get('etag');

  // Content-level change check. If the server rotated ETags without
  // actually changing bytes, don't re-write the file (saves a noisy git
  // diff on the tracked manifest), but *do* update the ETag so the next
  // run can conditional-hit with the new value.
  if (prior && prior.sha256 === sha && existsSync(targetPath)) {
    return {
      outcome: { kind: 'bytes-same', bytes: bytes.byteLength },
      nextEntry: {
        ...prior,
        etag: newEtag,
        url: source.url,
        lastCheckedAt: nowIso,
      },
    };
  }

  // Real update: write the file, bump both timestamps.
  mkdirSync(VENDOR_DIR, { recursive: true });
  writeFileSync(targetPath, bytes);

  const nextEntry: ListManifestEntry = {
    url: source.url,
    etag: newEtag,
    sha256: sha,
    bytes: bytes.byteLength,
    lastFetchedAt: nowIso,
    lastCheckedAt: nowIso,
  };

  const outcome: FetchOutcome = prior
    ? {
        kind: 'updated',
        bytes: bytes.byteLength,
        oldBytes: prior.bytes,
      }
    : { kind: 'first-fetch', bytes: bytes.byteLength };

  return { outcome, nextEntry };
}

// ---------------------------------------------------------------------------
// CLI summary formatting.
// ---------------------------------------------------------------------------

// Pin the locale so output is identical across dev machines — `toLocaleString()`
// with no args honors the system locale, which caused "22,61,558 bytes"
// (Indian numbering) on the first dev box that ran this.
const nf = new Intl.NumberFormat('en-US');

function describeOutcome(id: string, outcome: FetchOutcome): string {
  switch (outcome.kind) {
    case 'first-fetch':
      return `  + ${id}: fetched (${nf.format(outcome.bytes)} bytes)`;
    case 'updated': {
      const delta = outcome.bytes - outcome.oldBytes;
      const sign = delta >= 0 ? '+' : '';
      return `  ~ ${id}: updated (${nf.format(outcome.bytes)} bytes, ${sign}${nf.format(delta)})`;
    }
    case 'etag-same':
      return `  = ${id}: cached (304 Not Modified)`;
    case 'bytes-same':
      return `  = ${id}: cached (ETag changed, content identical)`;
  }
}

// ---------------------------------------------------------------------------
// Public entry point — exported for tests or programmatic callers.
// ---------------------------------------------------------------------------

export interface FetchAllResult {
  outcomes: Array<{ id: string; outcome: FetchOutcome }>;
  manifest: VendorManifest;
}

export async function fetchAll(
  sources: readonly ListSource[] = SOURCES,
): Promise<FetchAllResult> {
  const manifest = loadManifest();
  const outcomes: FetchAllResult['outcomes'] = [];

  // Serial rather than Promise.all — upstream is a CDN and we're only
  // hitting two URLs, but the serial form gives cleaner log ordering and
  // avoids the (rare) case of two concurrent manifest writes racing on a
  // slow disk. If we ever grow to tens of lists, revisit.
  for (const source of sources) {
    const prior = manifest.entries[source.id];
    const { outcome, nextEntry } = await fetchList(source, prior);
    manifest.entries[source.id] = nextEntry;
    outcomes.push({ id: source.id, outcome });
  }

  saveManifest(manifest);
  return { outcomes, manifest };
}

// ---------------------------------------------------------------------------
// CLI entry.
// ---------------------------------------------------------------------------

const isMain = (() => {
  if (!process.argv[1]) return false;
  const invoked = resolve(process.argv[1]);
  const self = fileURLToPath(import.meta.url);
  return resolve(self) === invoked;
})();

if (isMain) {
  fetchAll()
    .then((r) => {
      process.stderr.write('ad-blocker fetch-lists\n');
      for (const { id, outcome } of r.outcomes) {
        process.stderr.write(describeOutcome(id, outcome) + '\n');
      }
      process.stderr.write(`  manifest: ${MANIFEST_PATH}\n`);
    })
    .catch((err) => {
      process.stderr.write(`fetch-lists failed: ${String(err)}\n`);
      process.exit(1);
    });
}
